noun = input("Enter a noun: ")
verb1 = input("Enter a verb: ")
color1 = input("Enter a color: ")
pn = input("Enter a plural noun: ")
verb2 = input("Enter another verb: ")
color2 = input("Enter another color: ")
person = input("Enter a person: ")
verb3 = input("Enter another verb: ")
cel = input("Enter a celebrity: ")

print("\n")
print(noun + " " + verb1 + " " + color1)
print(pn + " " + verb2 + " " + color2)
print(person + " " + verb3 + " " + cel)
